name: VencoPy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - jupyterlab
  - matplotlib
  - openpyxl
  - pandas=1.1.1
  - python=3.7
  - pyyaml
  - seaborn
  - sphinx
  - sphinx_rtd_theme
  - xlrd=1.2.0
  - yaml
