#-*- coding:utf-8 -*-

# __version__ = '0.0.8'
# __maintainer__ = 'Niklas Wulff 2019-02-12'
# __email__ = 'Niklas.Wulff@dlr.de'
# __birthdate__ = '2019-02-12'
# __status__ = 'test'  # options are: dev, test, prod

# This config holds all relative paths and filenames for VencoPy

linksRelative:
    input: ./inputData/
    plots: ./output/plots/
    resultsDaily: ./output/dailyTimeseries/
    resultsAnnual: ./output/annualTimeseries/
    scripts: ./scripts/
    config: ./config/
    outputConfig: ./config/outputConfigREMix.yaml

linksAbsolute:
    someLinkOnHardDrive:

files:
    inputDataScalars: VencoPy_scalarInput.xlsx
    inputDataDriveProfiles: inputProfiles_Drive.csv
    inputDataPlugProfiles: inputProfiles_Plug.csv

labels:
    technologyLabel: BEV-S
    outputFileName: VencoPy_MR1_alpha1_batCap40_cons15

postprocessing:
    hoursClone: 8760